# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    generate_address:
        class: AppBundle\Service\GenerateAddress
        arguments:
            - "@doctrine.orm.entity_manager"

    geocode:
        class: AppBundle\Service\GeoCode
        arguments:
            - "@csa_guzzle.client.geocoding"
            - "@doctrine.orm.entity_manager"
            - "@logger"
            - "%maps_apikey%"

    set_coordinates:
        class: AppBundle\Service\SetCoordinates
        autowire: true

    export_geo_json:
        class: AppBundle\Service\ExportGeoJSON
        autowire: true
